### ISSUE TITLE
功能性问题

### ISSUE THREAD

**Issue by githeer** [zqisheng/QsBle#1]
有自动重连功能吗？

**Comment by zqisheng** [comment]
这个功能可以加上,等下会加个非代码主动断开设备连接后重新连接的功能

**Comment by zqisheng** [comment]
> 有自动重连功能吗？

这个功能可以加上,等下会加个非代码主动断开设备连接的重新连接的功能

**Comment by githeer** [comment]
startScan 之前可以加个扫描列表的条件过滤，mac， 广播名，uuid等

**Comment by zqisheng** [comment]
> startScan 之前可以加个扫描列表的条件过滤，mac， 广播名，uuid等

有过滤的操作
这个方法config参数可以过滤
public void startScan(long time, IScanCallback callback, WrapScanConfig config)
链式的扫描操作
QsBle.getInstance().chain(mac)
            //chain中传入mac就是只扫描这个mac的设备
            //没有传的话不会过滤mac
            .startScan()
            //过滤的广播name
            .filterName(name)
            //过滤的service uuid
            .filterServiceUuids(uuid)
            //扫描的时间
            .scanTime(20000)
            .start()
后续会完善文档

**Comment by githeer** [comment]
/**
     * 设置非代码断开设备自动重连次数
     * 如果不是app端主动断开,会按照设置的值进行重连,默认是0,不进行重连
     * @param mac
     * @param autoReconnectCount 这个值会覆盖 BleGlobalConfig.autoReconnectCount 的默认设置
     */
    public void setAutoReconnectCount(String mac,int autoReconnectCount){
        sendMessage(new AbsMessage() {
            @Override
            public void onHandlerMessage() {
                if (BleDebugConfig.isDebug){
                    BleLog.d(String.format("setAutoReconnectCount mac=%s,autoReconnectCount=%d", mac, autoReconnectCount));
                }
                ble.setAutoReconnectCount(mac, autoReconnectCount);
            }
        });
    }

少一个功能，就是有之前连接过的，下次打开APP扫描到后自动连接

**Comment by githeer** [comment]
今天试了下demo。请问下，打开通知后，消息回调是哪个，试了两个都没有打印消息

**Comment by zqisheng** [comment]
> 今天试了下demo。请问下，打开通知后，消息回调是哪个，试了两个都没有打印消息

public void addChacChangeCallback(String mac,Lifecycle lifecycle, IChacChangeCallback callback)
打开通知后,用这个方法添加设备发送消息过来的回调

**Comment by githeer** [comment]
分包能出个demo代码不，当有mtu长度和超过mtu长度消息，接收的时候 addChacChangeCallback  和 addBleMultiPkgsCallback这个两个消息监听如何处理呢，长度以内走前者，超出长度的通过后者回调吗？

**Comment by githeer** [comment]
当设备有多个时，怎么动态添加回调呢

**Comment by zqisheng** [comment]
1.每个公司定的分包协议都不一样，不过一般协议里面都定义了包序号和最后一包的标识，自己看组包的抽象类，实现方法就行
addChacChangeCallback是特征值改变就回调，是以一个mtu为单位的，addBleMultiPkgsCallback这个方法是建立在addChacChangeCallback这个方法之上实现的
2.多个设备，自己添加回调就行了，添加回调不是有mac地址的参数吗

**Comment by githeer** [comment]
> 1.每个公司定的分包协议都不一样，不过一般协议里面都定义了包序号和最后一包的标识，自己看组包的抽象类，实现方法就行 addChacChangeCallback是特征值改变就回调，是以一个mtu为单位的，addBleMultiPkgsCallback这个方法是建立在addChacChangeCallback这个方法之上实现的 2.多个设备，自己添加回调就行了，添加回调不是有mac地址的参数吗

当设备是动态添加删除时，这个就适用了，能不能注册一次回调，interface里每次返回不用的mac。然后用户根据mac去处理先关的事务。这样好像好点

**Comment by zqisheng** [comment]
版本1.2.2已经添加了 setGlobalGattCallback 全局回调的方法
