### ISSUE TITLE
框架不支持后台扫描

### ISSUE THREAD

**Issue by sdjwj1118** [zqisheng/QsBle#3]
有业务需求需要在后台也进行扫描，在service中无法扫描设备

**Comment by zqisheng** [comment]
Ble复杂的扫描这块,你可以使用这个框架,QsBle只是对扫描做了简单的封装,对应复杂的扫描逻辑实现,可以使用我推荐的这个库,这个库对各个版本的Android做了适配和同一实现,你可以扫描逻辑使用Android-Scanner-Compat-Library框架,连接后的操作使用QsBle框架
https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library
