### ISSUE TITLE
安卓9以上搜索蓝牙设备 获取不到蓝牙的名称呢？ 

### ISSUE THREAD

**Issue by hekaiaichengjing** [zqisheng/QsBle#4]
安卓9以上搜索蓝牙设备 获取不到蓝牙的名称呢？ 谢谢 望处理

**Comment by zqisheng** [comment]
你使用其它框架能否获得设备的名称?我这边测试了是没有问题的

**Comment by hekaiaichengjing** [comment]
验证了一下 是自己设备这边的问题 谢谢
&nbsp;


踏ˉ云海之人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 晚上6:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zqisheng/QsBle] 安卓9以上搜索蓝牙设备 获取不到蓝牙的名称呢？  (Issue #4)





 
你使用其它框架能否获得设备的名称?我这边测试了是没有问题的
